server:
  shutdown: graceful

spring:
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/playground
    username: root
    password: root

  flyway:
    enabled: true
    create-schemas: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 500

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    com.tistory.devs0n.cdc: DEBUG
