spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/playground?replicaSet=rs&readPreference=secondaryPreferred&minpoolsize=5&maxpoolsize=5

logging:
  level:
    org.springframework.data.mongodb: DEBUG
