server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client: # eureka library 는 client 로서 서버에 등록을 하려고 함: 서버 등록 기능 꺼야함
    register-with-eureka: false
    fetch-registry: false
