server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user
    username: root
    password: root
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      - http://localhost:8761/eureka

logging:
  level:
    org.springframework.jdbc.core: TRACE
    com.tistory.devs0n.user: DEBUG

config:
  auth:
    secret: mysecret
    token-expiration-hour: 24

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, busrefresh, info, prometheus, metrics

#spring:
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

feign:
  client:
    config:
      default:
        loggerLevel: full
