server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file://${user.home}/tmp/spring-cloud-config-repo
        git:
          uri: /Users/son/tmp/spring-cloud-config-repo  # local
#          uri: https://github.com/ivvve/spring-cloud-config-repo.git  # remote
#          username: <gitgub username>
#          password: <github password>

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
