server:
  port: 0

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_catalog
    username: root
    password: root

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      - http://localhost:8761/eureka

logging:
  level:
    org.springframework.jdbc.core: TRACE
